# Generated by Django 2.2.8 on 2020-03-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200319_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_comment',
            new_name='approve_comment',
        ),
    ]
